### ISSUE TITLE
Packaging pydevd_attach_to_process as something importable

### ISSUE THREAD

**Issue by ionelmc** [fabioz/PyDev.Debugger#99] opened 2017-09-03 15:44 UTC
Hello,

I was wondering why the pydevd_attach_to_process stuff is packaged as data files instead of a normal package. It could go in sys.prefix or site-packages depending on how https://pypi.python.org/pypi/pydevd is installed.

Currently you have to figure out where the files are, you can't simply import stuff from pydevd_attach_to_process. 

How are users expected to use this part of pydevd? Can this be changed?

**Comment by ionelmc** [comment] 2017-09-04 22:40
@fabioz or maybe I should just vendor those files? Would it be ok to include them in BSD-licensed project?

**Comment by fabioz** [comment] 2017-09-05 00:02
This is by design... the main reason is that this isn't meant to be used as a python module... it should be used as a main which should be run in a python interpreter which matches the architecture of the interpreter that we'll attach to (i.e.: call `attach_pydevd.py` with the proper port/pid where the remote debugger is listening).

Regarding vendoring it, it's license is EPL -- as far as I know, it should be Ok, although you probably have to mention that you have an EPL'd module included (you should be able to add EPL'd code in a bigger project without having to change it -- you just need to provide back sources to your modifications -- as an example, PyCharm bundles it both in their commercial offering as well as their open source version)... although I'm not a lawyer, so, you should probably read the actual EPL license to check if it's really Ok for your use case ;)

I'm also curious on which project you're interested in including pydevd support ;)

**Comment by ionelmc** [comment] 2017-09-05 00:08
In this https://github.com/ionelmc/python-hunter - I've recently added support for [tracing other processes](https://python-hunter.readthedocs.io/en/latest/remote.html) but now I'm thinking how to support more platforms. Injecting code in Windows processes is way over my head so I thought I could just reuse the awesome injection stuff from pydevd.

**Comment by fabioz** [comment] 2017-09-05 12:14
I think you can reuse it, but you may need to do some work to integrate... at minimum you'll need a different attach_script (https://github.com/fabioz/PyDev.Debugger/blob/master/pydevd_attach_to_process/attach_script.py).

p.s.: I'm closing the issue as I don't think there's much to do on my side, but feel free to provide a pull request if you feel some change could help you in the integration.

**Closed by fabioz** 2017-09-05 12:14 UTC

**Comment by ionelmc** [comment] 2017-09-13 22:21
@fabioz Can you give me a quick overview (right places to look in code) on how tracers are installed on all the threads? Or at least confirm that I got this right: the dll/so helpers have the ability to install a tracer on all threads (via `SetSysTraceFunc`) but it's hardcoded to `pydevd.trace_dispatch`. So that means I'd need to patch the sources and recompile all the helpers right?

Also, is there any particular reason the GDB backend (`run_python_code_linux`) couldn't work on OSX?

**Comment by fabioz** [comment] 2017-09-14 10:33
@ionelmc You're looking at the right place (`SetSysTraceFunc` is the place -- the line `curFrame->f_trace = traceFunc.ToPython();` is where it sets the tracing for the frame and `DecRef(call(settrace.ToPython(), traceFunc.ToPython(), NULL), isDebug);` is where it calls `sys.settrace` there and yes, things are hard-coded for the PyDev debugger).

Related to the Linux backend, the problem is that latest versions of OSX don't ship with GDB, they ship with LLDB (but apart from that, if the user actually had GDB installed on OSX, it should work, although I haven't really tested it).

**Comment by ionelmc** [comment] 2017-09-14 11:43
@fabioz any specific instructions for building the helpers? what OS versions do you use to build them?

**Comment by fabioz** [comment] 2017-09-14 12:36
Well, they're pretty simple (see compile_so.sh, compile_mac.sh and compile_dll.bat -- I just run them on the command line). 

On Linux/Mac it should be a version with the oldest libc you want to support. For Windows I used VisualStudio 14, but other versions should work too.
