### ISSUE TITLE
Pydevd not working with Unreal python integration

### ISSUE THREAD

**Issue by allender** [fabioz/PyDev.Debugger#207] opened 2021-12-14 22:58 UTC
I am running unreal (5 pre-access, but I don't think that matters), and I wanted to install pydevd so that I would be able to debug python code that I was writing for the Unreal editor.   Unreal has it's own embedded python 3.7.7 interpreter (which as I looked, is stock 3.7.7 - there appear to be no modifications to the python code in unreal).  

For starters, I pip installed pydevd into a standalone python 3.7 folder (not the unreal one).  In my unreal python code, I added that installed location to my sys.path, imported pydevd, and everything worked great.  Then I wanted to actually move pydevd into the actual python folder in unreal.  I was able to pip install to the right location.  Importing pydevd worked, but with this error:

     pydev_log.critical('This version of python seems to be incorrectly compiled')
        pydev_log.critical('(internal generated filenames are not absolute).')
        pydev_log.critical('This may make the debugger miss breakpoints.')
        pydev_log.critical('Related bug: http://bugs.python.org/issue1666807')

It turns out that this issue started [here](https://github.com/microsoft/debugpy/issues/52).  Looking for the module pathname changed from _Normfile to os.path.isabs.  Using _Normfile works.  In tracing through initialization from import pydevd, the code in pydev_file_utils.py gets run.  The first path it gets is:

../../../Engine/Binaries/ThirdParty/Python3/Win64\lib\ntpath.py

from os.path.relpath.   Obviously this is a relative path and that fails the current isabs(code.co_filename) call that is currently there.  Rolling back to the _Normfile call, it will work because the path is turned into an absolute path.  For reasons that I don't fully understand, the file attribute of the __code__ attribute for relpath is absolute when it's run inside the intepreter inside of Unreal.  Running the standalone python interpreter with Unreal gives absolute paths.

I'm not entirely sure why there is a difference between the embedded interpreter and the standalone interpreter for these code path attributes, but clearly the internal interpreter is giving me relative paths that need to be normalized.

**Comment by allender** [comment] 2021-12-17 17:38
Updated issue with more information about when this seemed to stop working in the pydevd codeline

**Comment by fabioz** [comment] 2021-12-17 17:44
Sorry for the delay in getting back to you.

So, as you've seen, the check that is done there is that it gets a function from the os module (namely `os.path.realpath`) then gets its code and checks if the filename is absolute or not -- because if the paths are relative, the paths can't be resolved properly (as the filename will depend on your `cwd`).

I must say I don't really know how paths end up being relative (all I know is that this seems to depend on how Python itself was built).

There are some workarounds in code to try to work around that (you can see that `pydevd_file_utils._get_relative_filename_abs_path` will try to resolve a relative path by checking the relative paths vs all the entries in `sys.path`), so, in many cases it may still work.

It'd be interesting if you can provide the logs for the case where you add a breakpoint and it's being missed (to see the actual filenames being generated in your use case).

To do that you can set as environment variables:

`PYDEV_DEBUG=1`
`PYDEVD_DEBUG_FILE=<path/to/file.log>` (substituting for a proper path in your machine)

and then attach the generated log files to this issue.

**Comment by allender** [comment] 2021-12-17 18:09
I have a log file for this issue.  It does contain some sensitive data that will be difficult to strip out in order to show you what you need to know.  Is there a way I can privately send you the file?

**Comment by fabioz** [comment] 2021-12-17 18:11
> I have a log file for this issue. It does contain some sensitive data that will be difficult to strip out in order to show you what you need to know. Is there a way I can privately send you the file?

Yes, you can send it to fabiofz at gmail.com.

**Comment by fabioz** [comment] 2021-12-17 18:35
Closing issue since the logs indicate that everything is correct (it seems that the issue is that `pydevd` is being used with `PyCharm`, which has its own fork and may have deviated from the `pydevd` protocol).

**Closed by fabioz** 2021-12-17 18:35 UTC

**Comment by allender** [comment] 2021-12-17 18:37
Ok -  thank you.  I wondered if that was the case after looking at the log file that was generated.  Sorry to bother you with pycharm issue, but I appreciate the assist in figuring out where the problem is.
