### ISSUE TITLE
A new lines in the output

### ISSUE THREAD

**Issue by Elizaveta239** [fabioz/PyDev.Debugger#45] opened 2016-01-21 15:55 UTC
Every time the debugger stops at the breakpoint, the new empty line appears in the output. Are you able to reproduce it in the Eclipse?
I failed to find the forgotten `print` statement inside the debugger.

**Comment by fabioz** [comment] 2016-01-21 16:13
Hi Elizaveta,

I don't have this behavior in PyDev... (on a regular debug session, I don't have anything going to stdout/stderr when I hit a breakpoint). I also gave a look on the code looking for `print` and `.write` and couldn't find something I thought could be related to this.

To diagnose it there, you could try overriding stdout/stderr in the Python side and giving an error on write (whitelisting the writes you expect to happen), so, if you don't have anything on the backend it should be a signal it's something on the PyCharm side (otherwise, it should be easy to spot the write on the backend).

Note that I'm closing because I can't reproduce, but feel free to reopen if you think there's a special circumstance where it happens which I didn't consider or more info on how to reproduce.

**Closed by fabioz** 2016-01-21 16:13 UTC
